<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/Dialog_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select Dialog.d_id as 'D_id', player2.p_name as 'From_p_id', player3.p_name as 'To_p_id', Dialog.d_message as 'Message' from Dialog LEFT JOIN player as player2 ON Dialog.d_from_p_id=player2.p_id LEFT JOIN player as player3 ON Dialog.d_to_p_id=player3.p_id ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select Dialog.d_id as 'D_id', concat(player2.p_name, '') as 'From_p_id', concat(player3.p_name, '') as 'To_p_id', Dialog.d_message as 'Message' from Dialog LEFT JOIN player as player2 ON Dialog.d_from_p_id=player2.p_id LEFT JOIN player as player3 ON Dialog.d_to_p_id=player3.p_id ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Dialog_view.php";
	$x->RedirectAfterInsert = "Dialog_view.php?SelectedID=#ID#";
	$x->TableTitle = "Dialog";
	$x->PrimaryKey = "Dialog.d_id";

	$x->ColWidth   = array(150, 150, 150);
	$x->ColCaption = array("From_p_id", "To_p_id", "Message");
	$x->ColNumber  = array(2, 3, 4);

	$x->Template = 'Dialog_templateTV.html';
	$x->SelectedTemplate = 'Dialog_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>