<?php

// Data functions for table Dialog

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$d_from_p_id = $HTTP_POST_VARS["d_from_p_id"];
		$d_to_p_id = $HTTP_POST_VARS["d_to_p_id"];
		$d_message = $HTTP_POST_VARS["d_message"];
	}
	else
	{
		$d_from_p_id = addslashes($HTTP_POST_VARS["d_from_p_id"]);
		$d_to_p_id = addslashes($HTTP_POST_VARS["d_to_p_id"]);
		$d_message = addslashes($HTTP_POST_VARS["d_message"]);
	}
	
	sql("insert into Dialog (d_message) values (" . (($d_message != "") ? "'$d_message'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	sql("delete from Dialog where d_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$d_from_p_id = $HTTP_POST_VARS["d_from_p_id"];
		$d_to_p_id = $HTTP_POST_VARS["d_to_p_id"];
		$d_message = $HTTP_POST_VARS["d_message"];
	}
	else
	{
		$d_from_p_id = addslashes($HTTP_POST_VARS["d_from_p_id"]);
		$d_to_p_id = addslashes($HTTP_POST_VARS["d_to_p_id"]);
		$d_message = addslashes($HTTP_POST_VARS["d_message"]);
	}

	sql("update Dialog set " . "d_message=" . (($d_message != "") ? "'$d_message'" : "NULL") . " where d_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: d_from_p_id
	$combo_d_from_p_id = new DataCombo;
	$combo_d_from_p_id->Query = "select p_id, concat(p_name, '') from player order by 2";
	$combo_d_from_p_id->SelectName = "d_from_p_id";
	// combobox: d_to_p_id
	$combo_d_to_p_id = new DataCombo;
	$combo_d_to_p_id->Query = "select p_id, concat(p_name, '') from player order by 2";
	$combo_d_to_p_id->SelectName = "d_to_p_id";

	if($selected_id)
	{
		$res = sql("select * from Dialog where d_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_d_from_p_id->SelectedData = $row["d_from_p_id"];
		$combo_d_to_p_id->SelectedData = $row["d_to_p_id"];
	}
	$combo_d_from_p_id->Render();
	$combo_d_to_p_id->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./Dialog_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(d_from_p_id)%%>', $combo_d_from_p_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(d_from_p_id)%%>', $combo_d_from_p_id->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(d_to_p_id)%%>', $combo_d_to_p_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(d_to_p_id)%%>', $combo_d_to_p_id->MatchText, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(d_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(d_from_p_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(d_to_p_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(d_message)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(d_id)%%>', htmlspecialchars($row['d_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_id)%%>', htmlspecialchars($row['d_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_from_p_id)%%>', htmlspecialchars($row['d_from_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_from_p_id)%%>', htmlspecialchars($row['d_from_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_to_p_id)%%>', htmlspecialchars($row['d_to_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_to_p_id)%%>', htmlspecialchars($row['d_to_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_message)%%>', htmlspecialchars($row['d_message'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(d_message)%%>', htmlspecialchars($row['d_message'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(d_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(d_from_p_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(d_to_p_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(d_message)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>