<?php

// Data functions for table locations

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$l_active = $HTTP_POST_VARS["l_active"];
		$l_name = $HTTP_POST_VARS["l_name"];
		$l_adr = $HTTP_POST_VARS["l_adr"];
		$l_zip = $HTTP_POST_VARS["l_zip"];
		$l_mail = $HTTP_POST_VARS["l_mail"];
		$l_desc = $HTTP_POST_VARS["l_desc"];
		$l_phone1 = $HTTP_POST_VARS["l_phone1"];
		$l_phone2 = $HTTP_POST_VARS["l_phone2"];
		$l_open = $HTTP_POST_VARS["l_open"];
		$l_close = $HTTP_POST_VARS["l_close"];
	}
	else
	{
		$l_active = addslashes($HTTP_POST_VARS["l_active"]);
		$l_name = addslashes($HTTP_POST_VARS["l_name"]);
		$l_adr = addslashes($HTTP_POST_VARS["l_adr"]);
		$l_zip = addslashes($HTTP_POST_VARS["l_zip"]);
		$l_mail = addslashes($HTTP_POST_VARS["l_mail"]);
		$l_desc = addslashes($HTTP_POST_VARS["l_desc"]);
		$l_phone1 = addslashes($HTTP_POST_VARS["l_phone1"]);
		$l_phone2 = addslashes($HTTP_POST_VARS["l_phone2"]);
		$l_open = addslashes($HTTP_POST_VARS["l_open"]);
		$l_close = addslashes($HTTP_POST_VARS["l_close"]);
	}
	if($l_zip == "") $l_zip = "0";
	
	sql("insert into locations (l_active, l_name, l_adr, l_zip, l_mail, l_desc, l_phone1, l_phone2, l_open, l_close) values (" . (($l_active != "") ? "'$l_active'" : "NULL") . ", " . (($l_name != "") ? "'$l_name'" : "NULL") . ", " . (($l_adr != "") ? "'$l_adr'" : "NULL") . ", " . (($l_zip != "") ? "'$l_zip'" : "NULL") . ", " . (($l_mail != "") ? "'$l_mail'" : "NULL") . ", " . (($l_desc != "") ? "'$l_desc'" : "NULL") . ", " . (($l_phone1 != "") ? "'$l_phone1'" : "NULL") . ", " . (($l_phone2 != "") ? "'$l_phone2'" : "NULL") . ", " . (($l_open != "") ? "'$l_open'" : "NULL") . ", " . (($l_close != "") ? "'$l_close'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;

	// child table: player
	$res = sql("select l_id from locations where l_id='".addslashes($selected_id)."'");
	$l_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from player where p_location='".addslashes($l_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='locations_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='locations_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	

	sql("delete from locations where l_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$l_active = $HTTP_POST_VARS["l_active"];
		$l_name = $HTTP_POST_VARS["l_name"];
		$l_adr = $HTTP_POST_VARS["l_adr"];
		$l_zip = $HTTP_POST_VARS["l_zip"];
		$l_mail = $HTTP_POST_VARS["l_mail"];
		$l_desc = $HTTP_POST_VARS["l_desc"];
		$l_phone1 = $HTTP_POST_VARS["l_phone1"];
		$l_phone2 = $HTTP_POST_VARS["l_phone2"];
		$l_open = $HTTP_POST_VARS["l_open"];
		$l_close = $HTTP_POST_VARS["l_close"];
	}
	else
	{
		$l_active = addslashes($HTTP_POST_VARS["l_active"]);
		$l_name = addslashes($HTTP_POST_VARS["l_name"]);
		$l_adr = addslashes($HTTP_POST_VARS["l_adr"]);
		$l_zip = addslashes($HTTP_POST_VARS["l_zip"]);
		$l_mail = addslashes($HTTP_POST_VARS["l_mail"]);
		$l_desc = addslashes($HTTP_POST_VARS["l_desc"]);
		$l_phone1 = addslashes($HTTP_POST_VARS["l_phone1"]);
		$l_phone2 = addslashes($HTTP_POST_VARS["l_phone2"]);
		$l_open = addslashes($HTTP_POST_VARS["l_open"]);
		$l_close = addslashes($HTTP_POST_VARS["l_close"]);
	}

	sql("update locations set " . "l_active=" . (($l_active != "") ? "'$l_active'" : "NULL") . ", " . "l_name=" . (($l_name != "") ? "'$l_name'" : "NULL") . ", " . "l_adr=" . (($l_adr != "") ? "'$l_adr'" : "NULL") . ", " . "l_zip=" . (($l_zip != "") ? "'$l_zip'" : "NULL") . ", " . "l_mail=" . (($l_mail != "") ? "'$l_mail'" : "NULL") . ", " . "l_desc=" . (($l_desc != "") ? "'$l_desc'" : "NULL") . ", " . "l_phone1=" . (($l_phone1 != "") ? "'$l_phone1'" : "NULL") . ", " . "l_phone2=" . (($l_phone2 != "") ? "'$l_phone2'" : "NULL") . ", " . "l_open=" . (($l_open != "") ? "'$l_open'" : "NULL") . ", " . "l_close=" . (($l_close != "") ? "'$l_close'" : "NULL") . " where l_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: l_active
	$combo_l_active = new DataCombo;
	$combo_l_active->Query = "select xs_id, concat(xs_text, '') from xstatus order by 2";
	$combo_l_active->SelectName = "l_active";
	// combobox: l_zip
	$combo_l_zip = new DataCombo;
	$combo_l_zip->Query = "select ZZIP, concat(ZZCity, '') from ZZIP order by 2";
	$combo_l_zip->SelectName = "l_zip";

	if($selected_id)
	{
		$res = sql("select * from locations where l_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_l_active->SelectedData = $row["l_active"];
		$combo_l_zip->SelectedData = $row["l_zip"];
	}
	$combo_l_active->Render();
	$combo_l_zip->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./locations_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(l_active)%%>', $combo_l_active->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(l_active)%%>', $combo_l_active->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(l_zip)%%>', $combo_l_zip->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(l_zip)%%>', $combo_l_zip->MatchText, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(l_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_active)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_adr)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_zip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_mail)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_desc)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_phone1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_phone2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_open)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(l_close)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(l_id)%%>', htmlspecialchars($row['l_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_id)%%>', htmlspecialchars($row['l_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_active)%%>', htmlspecialchars($row['l_active'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%CHECKED(l_active)%%>', ($row['l_active'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_name)%%>', htmlspecialchars($row['l_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_name)%%>', htmlspecialchars($row['l_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_adr)%%>', htmlspecialchars($row['l_adr'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_adr)%%>', htmlspecialchars($row['l_adr'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_zip)%%>', htmlspecialchars($row['l_zip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_zip)%%>', htmlspecialchars($row['l_zip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_mail)%%>', htmlspecialchars($row['l_mail'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_mail)%%>', htmlspecialchars($row['l_mail'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_desc)%%>', htmlspecialchars($row['l_desc'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_desc)%%>', htmlspecialchars($row['l_desc'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone1)%%>', htmlspecialchars($row['l_phone1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone1)%%>', htmlspecialchars($row['l_phone1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone2)%%>', htmlspecialchars($row['l_phone2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone2)%%>', htmlspecialchars($row['l_phone2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_open)%%>', htmlspecialchars($row['l_open'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_open)%%>', htmlspecialchars($row['l_open'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_close)%%>', htmlspecialchars($row['l_close'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(l_close)%%>', htmlspecialchars($row['l_close'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(l_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(l_active)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_adr)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_zip)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_mail)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_desc)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_phone2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_open)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(l_close)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>