<?php

// Data functions for table mails

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$m_name = $HTTP_POST_VARS["m_name"];
		$m_body = $HTTP_POST_VARS["m_body"];
	}
	else
	{
		$m_name = addslashes($HTTP_POST_VARS["m_name"]);
		$m_body = addslashes($HTTP_POST_VARS["m_body"]);
	}
	
	sql("insert into mails (m_name, m_body) values (" . (($m_name != "") ? "'$m_name'" : "NULL") . ", " . (($m_body != "") ? "'$m_body'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	sql("delete from mails where m_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$m_name = $HTTP_POST_VARS["m_name"];
		$m_body = $HTTP_POST_VARS["m_body"];
	}
	else
	{
		$m_name = addslashes($HTTP_POST_VARS["m_name"]);
		$m_body = addslashes($HTTP_POST_VARS["m_body"]);
	}

	sql("update mails set " . "m_name=" . (($m_name != "") ? "'$m_name'" : "NULL") . ", " . "m_body=" . (($m_body != "") ? "'$m_body'" : "NULL") . " where m_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	

	if($selected_id)
	{
		$res = sql("select * from mails where m_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
	}
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./mails_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(m_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(m_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(m_body)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(m_id)%%>', htmlspecialchars($row['m_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(m_id)%%>', htmlspecialchars($row['m_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(m_name)%%>', htmlspecialchars($row['m_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(m_name)%%>', htmlspecialchars($row['m_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(m_body)%%>', htmlspecialchars($row['m_body'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(m_body)%%>', htmlspecialchars($row['m_body'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(m_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(m_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(m_body)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>