<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/mails_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select mails.m_id as 'Mid', mails.m_name as 'Mname', mails.m_body as 'M_body' from mails ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select mails.m_id as 'Mid', mails.m_name as 'Mname', mails.m_body as 'M_body' from mails ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "mails_view.php";
	$x->RedirectAfterInsert = "mails_view.php?SelectedID=#ID#";
	$x->TableTitle = "Mails";
	$x->PrimaryKey = "mails.m_id";
	$x->DefaultSortField = "2";
	$x->DefaultSortDirection = "asc";

	$x->ColWidth   = array(150, 150);
	$x->ColCaption = array("Mid", "Mname");
	$x->ColNumber  = array(1, 2);

	$x->Template = 'mails_templateTV.html';
	$x->SelectedTemplate = 'mails_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>