<?php

// Data functions for table news

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$n_active = $HTTP_POST_VARS["n_active"];
		$n_start = $HTTP_POST_VARS["n_startYear"] . '-' . $HTTP_POST_VARS["n_startMonth"] . '-' . $HTTP_POST_VARS["n_startDay"];
		$n_end = $HTTP_POST_VARS["n_endYear"] . '-' . $HTTP_POST_VARS["n_endMonth"] . '-' . $HTTP_POST_VARS["n_endDay"];
		$n_date = $HTTP_POST_VARS["n_dateYear"] . '-' . $HTTP_POST_VARS["n_dateMonth"] . '-' . $HTTP_POST_VARS["n_dateDay"];
		$n_head = $HTTP_POST_VARS["n_head"];
		$n_text = $HTTP_POST_VARS["n_text"];
		$n_link = $HTTP_POST_VARS["n_link"];
		$n_type = $HTTP_POST_VARS["n_type"];
	}
	else
	{
		$n_active = addslashes($HTTP_POST_VARS["n_active"]);
		$n_start = addslashes($HTTP_POST_VARS["n_startYear"]) . '-' . addslashes($HTTP_POST_VARS["n_startMonth"]) . '-' . addslashes($HTTP_POST_VARS["n_startDay"]);
		$n_end = addslashes($HTTP_POST_VARS["n_endYear"]) . '-' . addslashes($HTTP_POST_VARS["n_endMonth"]) . '-' . addslashes($HTTP_POST_VARS["n_endDay"]);
		$n_date = addslashes($HTTP_POST_VARS["n_dateYear"]) . '-' . addslashes($HTTP_POST_VARS["n_dateMonth"]) . '-' . addslashes($HTTP_POST_VARS["n_dateDay"]);
		$n_head = addslashes($HTTP_POST_VARS["n_head"]);
		$n_text = addslashes($HTTP_POST_VARS["n_text"]);
		$n_link = addslashes($HTTP_POST_VARS["n_link"]);
		$n_type = addslashes($HTTP_POST_VARS["n_type"]);
	}
	$n_file = PrepareUploadedFile('n_file', 2000000,'jpg|jpeg|gif|png', false, "");
	
	sql("insert into news (n_active, n_start, n_end, n_date, n_head, n_text, n_link, n_file, n_type) values (" . (($n_active != "") ? "'$n_active'" : "NULL") . ", " . (($n_start != "") ? "'$n_start'" : "NULL") . ", " . (($n_end != "") ? "'$n_end'" : "NULL") . ", " . (($n_date != "") ? "'$n_date'" : "NULL") . ", " . (($n_head != "") ? "'$n_head'" : "NULL") . ", " . (($n_text != "") ? "'$n_text'" : "NULL") . ", " . (($n_link != "") ? "'$n_link'" : "NULL") . ", " . (($n_file != "") ? "'$n_file'" : "NULL") . ", " . (($n_type != "") ? "'$n_type'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	// delete file stored in the 'n_file' field
	$res = sql("select n_file from news where n_id='".addslashes($selected_id)."'");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir("").$row[0]);
		}
	}

	sql("delete from news where n_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$n_active = $HTTP_POST_VARS["n_active"];
		$n_start = $HTTP_POST_VARS["n_startYear"] . '-' . $HTTP_POST_VARS["n_startMonth"] . '-' . $HTTP_POST_VARS["n_startDay"];
		$n_end = $HTTP_POST_VARS["n_endYear"] . '-' . $HTTP_POST_VARS["n_endMonth"] . '-' . $HTTP_POST_VARS["n_endDay"];
		$n_date = $HTTP_POST_VARS["n_dateYear"] . '-' . $HTTP_POST_VARS["n_dateMonth"] . '-' . $HTTP_POST_VARS["n_dateDay"];
		$n_head = $HTTP_POST_VARS["n_head"];
		$n_text = $HTTP_POST_VARS["n_text"];
		$n_link = $HTTP_POST_VARS["n_link"];
		$n_type = $HTTP_POST_VARS["n_type"];
	}
	else
	{
		$n_active = addslashes($HTTP_POST_VARS["n_active"]);
		$n_start = $HTTP_POST_VARS["n_startYear"] . '-' . $HTTP_POST_VARS["n_startMonth"] . '-' . $HTTP_POST_VARS["n_startDay"];
		$n_end = $HTTP_POST_VARS["n_endYear"] . '-' . $HTTP_POST_VARS["n_endMonth"] . '-' . $HTTP_POST_VARS["n_endDay"];
		$n_date = $HTTP_POST_VARS["n_dateYear"] . '-' . $HTTP_POST_VARS["n_dateMonth"] . '-' . $HTTP_POST_VARS["n_dateDay"];
		$n_head = addslashes($HTTP_POST_VARS["n_head"]);
		$n_text = addslashes($HTTP_POST_VARS["n_text"]);
		$n_link = addslashes($HTTP_POST_VARS["n_link"]);
		$n_type = addslashes($HTTP_POST_VARS["n_type"]);
	}

	if($HTTP_POST_VARS['n_file_remove'] == 1){
		$n_file = '';
		// delete file from server
		$res = sql("select n_file from news where n_id='$selected_id'");
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir("").$row[0]);
			}
		}
	}else{
		$n_file = PrepareUploadedFile('n_file', 2000000, 'jpg|jpeg|gif|png', false, "");
		// delete file from server
		if($n_file != ''){
			$res = sql("select n_file from news where n_id='$selected_id'");
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir("").$row[0]);
				}
			}
		}
	}
	sql("update news set " . "n_active=" . (($n_active != "") ? "'$n_active'" : "NULL") . ", " . "n_start=" . (($n_start != "") ? "'$n_start'" : "NULL") . ", " . "n_end=" . (($n_end != "") ? "'$n_end'" : "NULL") . ", " . "n_date=" . (($n_date != "") ? "'$n_date'" : "NULL") . ", " . "n_head=" . (($n_head != "") ? "'$n_head'" : "NULL") . ", " . "n_text=" . (($n_text != "") ? "'$n_text'" : "NULL") . ", " . "n_link=" . (($n_link != "") ? "'$n_link'" : "NULL") . ", " . ($n_file!="" ? "n_file='$n_file'" : ($HTTP_POST_VARS['n_file_remove'] != 1 ? "n_file=n_file" : "n_file=NULL")) . ", " . "n_type=" . (($n_type != "") ? "'$n_type'" : "NULL") . " where n_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: n_active
	$combo_n_active = new DataCombo;
	$combo_n_active->Query = "select xs_id, concat(xs_text, '') from xstatus order by 2";
	$combo_n_active->SelectName = "n_active";
	// combobox: n_start
	$combo_n_start = new DateCombo;
	$combo_n_start->DateFormat = "mdy";
	$combo_n_start->MinYear = 1900;
	$combo_n_start->MaxYear = 2100;
	$combo_n_start->DefaultDate = date("Y-m-d");
	$combo_n_start->MonthNames = $Translation['month names'];
	$combo_n_start->CSSOptionClass = 'Option';
	$combo_n_start->CSSSelectedClass = 'SelectedOption';
	$combo_n_start->NamePrefix = 'n_start';
	$n_startToday=" [<a href=\"javascript: return false;\" onClick=\"document.getElementById('n_startYear').value='".date("Y")."'; document.getElementById('n_startMonth').value='".date("m")."'; document.getElementById('n_startDay').value='".date("d")."';\">".$Translation['today']."</a>]";
	// combobox: n_end
	$combo_n_end = new DateCombo;
	$combo_n_end->DateFormat = "mdy";
	$combo_n_end->MinYear = 1900;
	$combo_n_end->MaxYear = 2100;
	$combo_n_end->DefaultDate = date("Y-m-d");
	$combo_n_end->MonthNames = $Translation['month names'];
	$combo_n_end->CSSOptionClass = 'Option';
	$combo_n_end->CSSSelectedClass = 'SelectedOption';
	$combo_n_end->NamePrefix = 'n_end';
	$n_endToday=" [<a href=\"javascript: return false;\" onClick=\"document.getElementById('n_endYear').value='".date("Y")."'; document.getElementById('n_endMonth').value='".date("m")."'; document.getElementById('n_endDay').value='".date("d")."';\">".$Translation['today']."</a>]";
	// combobox: n_date
	$combo_n_date = new DateCombo;
	$combo_n_date->DateFormat = "mdy";
	$combo_n_date->MinYear = 1900;
	$combo_n_date->MaxYear = 2100;
	$combo_n_date->DefaultDate = date("Y-m-d");
	$combo_n_date->MonthNames = $Translation['month names'];
	$combo_n_date->CSSOptionClass = 'Option';
	$combo_n_date->CSSSelectedClass = 'SelectedOption';
	$combo_n_date->NamePrefix = 'n_date';
	$n_dateToday=" [<a href=\"javascript: return false;\" onClick=\"document.getElementById('n_dateYear').value='".date("Y")."'; document.getElementById('n_dateMonth').value='".date("m")."'; document.getElementById('n_dateDay').value='".date("d")."';\">".$Translation['today']."</a>]";
	// combobox: n_type
	$combo_n_type = new Combo;
	$combo_n_type->ListType = 2;
	$combo_n_type->ListBoxHeight = 10;
	$combo_n_type->RadiosPerLine = 1;
	$combo_n_type->ListItem = explode(";;", "1;;2");
	$combo_n_type->ListData = explode(";;", "1;;2");
	$combo_n_type->SelectName = "n_type";

	if($selected_id)
	{
		$res = sql("select * from news where n_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_n_active->SelectedData = $row["n_active"];
		$combo_n_start->DefaultDate = $row["n_start"];
		$combo_n_end->DefaultDate = $row["n_end"];
		$combo_n_date->DefaultDate = $row["n_date"];
		$combo_n_type->SelectedData = $row["n_type"];
	}
	$combo_n_active->Render();
	$combo_n_type->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./news_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(n_active)%%>', $combo_n_active->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(n_active)%%>', $combo_n_active->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(n_start)%%>', $combo_n_start->GetHTML().$n_startToday, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(n_start)%%>', $combo_n_start->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(n_end)%%>', $combo_n_end->GetHTML().$n_endToday, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(n_end)%%>', $combo_n_end->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(n_date)%%>', $combo_n_date->GetHTML().$n_dateToday, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(n_date)%%>', $combo_n_date->GetHTML(true), $templateCode);
	$templateCode=str_replace('<%%COMBO(n_type)%%>', $combo_n_type->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(n_type)%%>', $combo_n_type->SelectedData, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(n_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_active)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_start)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_end)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_date)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_head)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_text)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_link)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_file)%%>', '<input type=hidden name=MAX_FILE_SIZE value=2000000>'.$Translation['upload image'].' <input type=file name="n_file" class=TextBox>', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(n_type)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(n_id)%%>', htmlspecialchars($row['n_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_id)%%>', htmlspecialchars($row['n_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_active)%%>', htmlspecialchars($row['n_active'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%CHECKED(n_active)%%>', ($row['n_active'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_start)%%>', htmlspecialchars($row['n_start'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_start)%%>', htmlspecialchars($row['n_start'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_end)%%>', htmlspecialchars($row['n_end'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_end)%%>', htmlspecialchars($row['n_end'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_date)%%>', htmlspecialchars($row['n_date'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_date)%%>', htmlspecialchars($row['n_date'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_head)%%>', htmlspecialchars($row['n_head'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_head)%%>', htmlspecialchars($row['n_head'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_text)%%>', htmlspecialchars($row['n_text'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_text)%%>', htmlspecialchars($row['n_text'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_link)%%>', htmlspecialchars($row['n_link'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_link)%%>', htmlspecialchars($row['n_link'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_file)%%>', htmlspecialchars($row['n_file'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_file)%%>', htmlspecialchars($row['n_file'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_type)%%>', htmlspecialchars($row['n_type'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(n_type)%%>', htmlspecialchars($row['n_type'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(n_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(n_active)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_start)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_end)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_date)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_head)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_text)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_link)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_file)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(n_type)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>