<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/player_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select xstatus2.xs_text as 'Active', locations3.l_name as 'Location', teams4.ts_name as 'P_s_id', player.p_first as 'P_first', player.p_name as 'Name', player.p_adr as 'Adr', ZZIP8.ZZIP as 'Zip', player.p_mail as 'Mail', player.p_newsaccept as 'Newsaccept', player.p_score as 'Score', player.p_scorehigh as 'P_scorehigh', player.p_games as 'P_games', player.p_time as 'Time', player.p_win as 'P_win', player.p_mk as 'P_mk', player.p_born as 'P_born', player.p_user as 'p_user', player.p_pwd as 'P_pwd', player.p_ip as 'IP Address', player.p_datetime as 'P_datetime', player.p_tscore as 'Turnament score', player.p_tkills as 'Turnament kills' from player LEFT JOIN xstatus as xstatus2 ON player.p_active=xstatus2.xs_id LEFT JOIN locations as locations3 ON player.p_location=locations3.l_id LEFT JOIN teams as teams4 ON player.p_s_id=teams4.ts_id LEFT JOIN ZZIP as ZZIP8 ON player.p_zip=ZZIP8.ZZIP ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select player.p_id as 'Pid', concat(xstatus2.xs_text, '') as 'Active', concat(locations3.l_name, '') as 'Location', concat(teams4.ts_name, '') as 'P_s_id', player.p_first as 'P_first', player.p_name as 'Name', player.p_adr as 'Adr', concat(ZZIP8.ZZIP, '', ZZIP8.ZZCity) as 'Zip', player.p_mail as 'Mail', concat('<img src=', if(player.p_newsaccept, 'checked.gif', 'checkednot.gif'), ' border=0>') as 'Newsaccept', player.p_score as 'Score', player.p_scorehigh as 'P_scorehigh', player.p_games as 'P_games', player.p_time as 'Time', player.p_win as 'P_win', player.p_mk as 'P_mk', player.p_born as 'P_born', player.p_user as 'p_user', player.p_pwd as 'P_pwd', player.p_ip as 'IP Address', player.p_datetime as 'P_datetime', player.p_tscore as 'Turnament score', player.p_tkills as 'Turnament kills' from player LEFT JOIN xstatus as xstatus2 ON player.p_active=xstatus2.xs_id LEFT JOIN locations as locations3 ON player.p_location=locations3.l_id LEFT JOIN teams as teams4 ON player.p_s_id=teams4.ts_id LEFT JOIN ZZIP as ZZIP8 ON player.p_zip=ZZIP8.ZZIP ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->AllowDelete = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "player_view.php";
	$x->RedirectAfterInsert = "player_view.php";
	$x->TableTitle = "Player";
	$x->PrimaryKey = "player.p_id";
	$x->DefaultSortField = "1";
	$x->DefaultSortDirection = "desc";

	$x->ColWidth   = array(50, 80, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Pid", "Active", "Location", "P_s_id", "P_first", "Name", "p_user", "IP Address");
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6, 18, 20);

	$x->Template = 'player_templateTV.html';
	$x->SelectedTemplate = 'player_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>