<?php

// Data functions for table Q1

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$Q1_work = $HTTP_POST_VARS["Q1_work"];
		$Q1_where = $HTTP_POST_VARS["Q1_where"];
		$Q1_why = $HTTP_POST_VARS["Q1_why"];
		$Q1_rating = $HTTP_POST_VARS["Q1_rating"];
		$Q1_speakothers = $HTTP_POST_VARS["Q1_speakothers"];
		$Q1_changedme = $HTTP_POST_VARS["Q1_changedme"];
		$Q1_playoften = $HTTP_POST_VARS["Q1_playoften"];
		$Q1_infolevel = $HTTP_POST_VARS["Q1_infolevel"];
		$Q1_SNotice = $HTTP_POST_VARS["Q1_SNotice"];
		$Q1_SNoticewhere = $HTTP_POST_VARS["Q1_SNoticewhere"];
		$Q1_SNoticemainsponsor = $HTTP_POST_VARS["Q1_SNoticemainsponsor"];
		$Q1_SNoticeteam = $HTTP_POST_VARS["Q1_SNoticeteam"];
		$Q1_SNoticeother = $HTTP_POST_VARS["Q1_SNoticeother"];
		$Q1_Shavechangedview = $HTTP_POST_VARS["Q1_Shavechangedview"];
		$Q1_Sbuyproducts = $HTTP_POST_VARS["Q1_Sbuyproducts"];
		$Q1_Snameothers = $HTTP_POST_VARS["Q1_Snameothers"];
		$Q1_Comments = $HTTP_POST_VARS["Q1_Comments"];
		$Q1_p_id = $HTTP_POST_VARS["Q1_p_id"];
	}
	else
	{
		$Q1_work = addslashes($HTTP_POST_VARS["Q1_work"]);
		$Q1_where = addslashes($HTTP_POST_VARS["Q1_where"]);
		$Q1_why = addslashes($HTTP_POST_VARS["Q1_why"]);
		$Q1_rating = addslashes($HTTP_POST_VARS["Q1_rating"]);
		$Q1_speakothers = addslashes($HTTP_POST_VARS["Q1_speakothers"]);
		$Q1_changedme = addslashes($HTTP_POST_VARS["Q1_changedme"]);
		$Q1_playoften = addslashes($HTTP_POST_VARS["Q1_playoften"]);
		$Q1_infolevel = addslashes($HTTP_POST_VARS["Q1_infolevel"]);
		$Q1_SNotice = addslashes($HTTP_POST_VARS["Q1_SNotice"]);
		$Q1_SNoticewhere = addslashes($HTTP_POST_VARS["Q1_SNoticewhere"]);
		$Q1_SNoticemainsponsor = addslashes($HTTP_POST_VARS["Q1_SNoticemainsponsor"]);
		$Q1_SNoticeteam = addslashes($HTTP_POST_VARS["Q1_SNoticeteam"]);
		$Q1_SNoticeother = addslashes($HTTP_POST_VARS["Q1_SNoticeother"]);
		$Q1_Shavechangedview = addslashes($HTTP_POST_VARS["Q1_Shavechangedview"]);
		$Q1_Sbuyproducts = addslashes($HTTP_POST_VARS["Q1_Sbuyproducts"]);
		$Q1_Snameothers = addslashes($HTTP_POST_VARS["Q1_Snameothers"]);
		$Q1_Comments = addslashes($HTTP_POST_VARS["Q1_Comments"]);
		$Q1_p_id = addslashes($HTTP_POST_VARS["Q1_p_id"]);
	}
	if($Q1_work == "") $Q1_work = "0";
	if($Q1_where == "") $Q1_where = "0";
	if($Q1_why == "") $Q1_why = "0";
	if($Q1_rating == "") $Q1_rating = "0";
	if($Q1_speakothers == "") $Q1_speakothers = "0";
	if($Q1_changedme == "") $Q1_changedme = "0";
	if($Q1_playoften == "") $Q1_playoften = "0";
	if($Q1_infolevel == "") $Q1_infolevel = "0";
	if($Q1_SNotice == "") $Q1_SNotice = "0";
	if($Q1_SNoticewhere == "") $Q1_SNoticewhere = "0";
	if($Q1_SNoticeteam == "") $Q1_SNoticeteam = "0";
	if($Q1_SNoticeother == "") $Q1_SNoticeother = "0";
	if($Q1_Shavechangedview == "") $Q1_Shavechangedview = "0";
	if($Q1_Sbuyproducts == "") $Q1_Sbuyproducts = "0";
	if($Q1_p_id == "") $Q1_p_id = "0";
	
	sql("insert into Q1 (Q1_work, Q1_where, Q1_why, Q1_rating, Q1_speakothers, Q1_changedme, Q1_playoften, Q1_infolevel, Q1_SNotice, Q1_SNoticewhere, Q1_SNoticemainsponsor, Q1_SNoticeteam, Q1_SNoticeother, Q1_Shavechangedview, Q1_Sbuyproducts, Q1_Snameothers, Q1_Comments, Q1_p_id) values (" . (($Q1_work != "") ? "'$Q1_work'" : "NULL") . ", " . (($Q1_where != "") ? "'$Q1_where'" : "NULL") . ", " . (($Q1_why != "") ? "'$Q1_why'" : "NULL") . ", " . (($Q1_rating != "") ? "'$Q1_rating'" : "NULL") . ", " . (($Q1_speakothers != "") ? "'$Q1_speakothers'" : "NULL") . ", " . (($Q1_changedme != "") ? "'$Q1_changedme'" : "NULL") . ", " . (($Q1_playoften != "") ? "'$Q1_playoften'" : "NULL") . ", " . (($Q1_infolevel != "") ? "'$Q1_infolevel'" : "NULL") . ", " . (($Q1_SNotice != "") ? "'$Q1_SNotice'" : "NULL") . ", " . (($Q1_SNoticewhere != "") ? "'$Q1_SNoticewhere'" : "NULL") . ", " . (($Q1_SNoticemainsponsor != "") ? "'$Q1_SNoticemainsponsor'" : "NULL") . ", " . (($Q1_SNoticeteam != "") ? "'$Q1_SNoticeteam'" : "NULL") . ", " . (($Q1_SNoticeother != "") ? "'$Q1_SNoticeother'" : "NULL") . ", " . (($Q1_Shavechangedview != "") ? "'$Q1_Shavechangedview'" : "NULL") . ", " . (($Q1_Sbuyproducts != "") ? "'$Q1_Sbuyproducts'" : "NULL") . ", " . (($Q1_Snameothers != "") ? "'$Q1_Snameothers'" : "NULL") . ", " . (($Q1_Comments != "") ? "'$Q1_Comments'" : "NULL") . ", " . (($Q1_p_id != "") ? "'$Q1_p_id'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	sql("delete from Q1 where Q1_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$Q1_work = $HTTP_POST_VARS["Q1_work"];
		$Q1_where = $HTTP_POST_VARS["Q1_where"];
		$Q1_why = $HTTP_POST_VARS["Q1_why"];
		$Q1_rating = $HTTP_POST_VARS["Q1_rating"];
		$Q1_speakothers = $HTTP_POST_VARS["Q1_speakothers"];
		$Q1_changedme = $HTTP_POST_VARS["Q1_changedme"];
		$Q1_playoften = $HTTP_POST_VARS["Q1_playoften"];
		$Q1_infolevel = $HTTP_POST_VARS["Q1_infolevel"];
		$Q1_SNotice = $HTTP_POST_VARS["Q1_SNotice"];
		$Q1_SNoticewhere = $HTTP_POST_VARS["Q1_SNoticewhere"];
		$Q1_SNoticemainsponsor = $HTTP_POST_VARS["Q1_SNoticemainsponsor"];
		$Q1_SNoticeteam = $HTTP_POST_VARS["Q1_SNoticeteam"];
		$Q1_SNoticeother = $HTTP_POST_VARS["Q1_SNoticeother"];
		$Q1_Shavechangedview = $HTTP_POST_VARS["Q1_Shavechangedview"];
		$Q1_Sbuyproducts = $HTTP_POST_VARS["Q1_Sbuyproducts"];
		$Q1_Snameothers = $HTTP_POST_VARS["Q1_Snameothers"];
		$Q1_Comments = $HTTP_POST_VARS["Q1_Comments"];
		$Q1_p_id = $HTTP_POST_VARS["Q1_p_id"];
	}
	else
	{
		$Q1_work = addslashes($HTTP_POST_VARS["Q1_work"]);
		$Q1_where = addslashes($HTTP_POST_VARS["Q1_where"]);
		$Q1_why = addslashes($HTTP_POST_VARS["Q1_why"]);
		$Q1_rating = addslashes($HTTP_POST_VARS["Q1_rating"]);
		$Q1_speakothers = addslashes($HTTP_POST_VARS["Q1_speakothers"]);
		$Q1_changedme = addslashes($HTTP_POST_VARS["Q1_changedme"]);
		$Q1_playoften = addslashes($HTTP_POST_VARS["Q1_playoften"]);
		$Q1_infolevel = addslashes($HTTP_POST_VARS["Q1_infolevel"]);
		$Q1_SNotice = addslashes($HTTP_POST_VARS["Q1_SNotice"]);
		$Q1_SNoticewhere = addslashes($HTTP_POST_VARS["Q1_SNoticewhere"]);
		$Q1_SNoticemainsponsor = addslashes($HTTP_POST_VARS["Q1_SNoticemainsponsor"]);
		$Q1_SNoticeteam = addslashes($HTTP_POST_VARS["Q1_SNoticeteam"]);
		$Q1_SNoticeother = addslashes($HTTP_POST_VARS["Q1_SNoticeother"]);
		$Q1_Shavechangedview = addslashes($HTTP_POST_VARS["Q1_Shavechangedview"]);
		$Q1_Sbuyproducts = addslashes($HTTP_POST_VARS["Q1_Sbuyproducts"]);
		$Q1_Snameothers = addslashes($HTTP_POST_VARS["Q1_Snameothers"]);
		$Q1_Comments = addslashes($HTTP_POST_VARS["Q1_Comments"]);
		$Q1_p_id = addslashes($HTTP_POST_VARS["Q1_p_id"]);
	}

	sql("update Q1 set " . "Q1_work=" . (($Q1_work != "") ? "'$Q1_work'" : "NULL") . ", " . "Q1_where=" . (($Q1_where != "") ? "'$Q1_where'" : "NULL") . ", " . "Q1_why=" . (($Q1_why != "") ? "'$Q1_why'" : "NULL") . ", " . "Q1_rating=" . (($Q1_rating != "") ? "'$Q1_rating'" : "NULL") . ", " . "Q1_speakothers=" . (($Q1_speakothers != "") ? "'$Q1_speakothers'" : "NULL") . ", " . "Q1_changedme=" . (($Q1_changedme != "") ? "'$Q1_changedme'" : "NULL") . ", " . "Q1_playoften=" . (($Q1_playoften != "") ? "'$Q1_playoften'" : "NULL") . ", " . "Q1_infolevel=" . (($Q1_infolevel != "") ? "'$Q1_infolevel'" : "NULL") . ", " . "Q1_SNotice=" . (($Q1_SNotice != "") ? "'$Q1_SNotice'" : "NULL") . ", " . "Q1_SNoticewhere=" . (($Q1_SNoticewhere != "") ? "'$Q1_SNoticewhere'" : "NULL") . ", " . "Q1_SNoticemainsponsor=" . (($Q1_SNoticemainsponsor != "") ? "'$Q1_SNoticemainsponsor'" : "NULL") . ", " . "Q1_SNoticeteam=" . (($Q1_SNoticeteam != "") ? "'$Q1_SNoticeteam'" : "NULL") . ", " . "Q1_SNoticeother=" . (($Q1_SNoticeother != "") ? "'$Q1_SNoticeother'" : "NULL") . ", " . "Q1_Shavechangedview=" . (($Q1_Shavechangedview != "") ? "'$Q1_Shavechangedview'" : "NULL") . ", " . "Q1_Sbuyproducts=" . (($Q1_Sbuyproducts != "") ? "'$Q1_Sbuyproducts'" : "NULL") . ", " . "Q1_Snameothers=" . (($Q1_Snameothers != "") ? "'$Q1_Snameothers'" : "NULL") . ", " . "Q1_Comments=" . (($Q1_Comments != "") ? "'$Q1_Comments'" : "NULL") . ", " . "Q1_p_id=" . (($Q1_p_id != "") ? "'$Q1_p_id'" : "NULL") . " where Q1_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: Q1_SNoticemainsponsor
	$combo_Q1_SNoticemainsponsor = new DataCombo;
	$combo_Q1_SNoticemainsponsor->Query = "select s_id, concat(s_id, ':', s_name) from sponsor order by 2";
	$combo_Q1_SNoticemainsponsor->SelectName = "Q1_SNoticemainsponsor";
	// combobox: Q1_SNoticeteam
	$combo_Q1_SNoticeteam = new DataCombo;
	$combo_Q1_SNoticeteam->Query = "select ts_id, concat(ts_name, '') from teams order by 2";
	$combo_Q1_SNoticeteam->SelectName = "Q1_SNoticeteam";
	// combobox: Q1_p_id
	$combo_Q1_p_id = new DataCombo;
	$combo_Q1_p_id->Query = "select p_id, concat(p_id, ':', p_mail) from player order by 2";
	$combo_Q1_p_id->SelectName = "Q1_p_id";

	if($selected_id)
	{
		$res = sql("select * from Q1 where Q1_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_Q1_SNoticemainsponsor->SelectedData = $row["Q1_SNoticemainsponsor"];
		$combo_Q1_SNoticeteam->SelectedData = $row["Q1_SNoticeteam"];
		$combo_Q1_p_id->SelectedData = $row["Q1_p_id"];
	}
	$combo_Q1_SNoticemainsponsor->Render();
	$combo_Q1_SNoticeteam->Render();
	$combo_Q1_p_id->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./Q1_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Answer for user', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(Q1_SNoticemainsponsor)%%>', $combo_Q1_SNoticemainsponsor->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Q1_SNoticemainsponsor)%%>', $combo_Q1_SNoticemainsponsor->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(Q1_SNoticeteam)%%>', $combo_Q1_SNoticeteam->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Q1_SNoticeteam)%%>', $combo_Q1_SNoticeteam->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(Q1_p_id)%%>', $combo_Q1_p_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(Q1_p_id)%%>', $combo_Q1_p_id->MatchText, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(Q1_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_work)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_where)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_why)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_rating)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_speakothers)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_changedme)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_playoften)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_infolevel)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_SNotice)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_SNoticewhere)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_SNoticemainsponsor)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_SNoticeteam)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_SNoticeother)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_Shavechangedview)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_Sbuyproducts)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_Snameothers)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_Comments)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(Q1_p_id)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(Q1_id)%%>', htmlspecialchars($row['Q1_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_id)%%>', htmlspecialchars($row['Q1_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_work)%%>', htmlspecialchars($row['Q1_work'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_work)%%>', htmlspecialchars($row['Q1_work'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_where)%%>', htmlspecialchars($row['Q1_where'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_where)%%>', htmlspecialchars($row['Q1_where'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_why)%%>', htmlspecialchars($row['Q1_why'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_why)%%>', htmlspecialchars($row['Q1_why'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_rating)%%>', htmlspecialchars($row['Q1_rating'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_rating)%%>', htmlspecialchars($row['Q1_rating'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_speakothers)%%>', htmlspecialchars($row['Q1_speakothers'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_speakothers)%%>', htmlspecialchars($row['Q1_speakothers'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_changedme)%%>', htmlspecialchars($row['Q1_changedme'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_changedme)%%>', htmlspecialchars($row['Q1_changedme'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_playoften)%%>', htmlspecialchars($row['Q1_playoften'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_playoften)%%>', htmlspecialchars($row['Q1_playoften'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_infolevel)%%>', htmlspecialchars($row['Q1_infolevel'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_infolevel)%%>', htmlspecialchars($row['Q1_infolevel'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNotice)%%>', htmlspecialchars($row['Q1_SNotice'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNotice)%%>', htmlspecialchars($row['Q1_SNotice'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticewhere)%%>', htmlspecialchars($row['Q1_SNoticewhere'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticewhere)%%>', htmlspecialchars($row['Q1_SNoticewhere'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticemainsponsor)%%>', htmlspecialchars($row['Q1_SNoticemainsponsor'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticemainsponsor)%%>', htmlspecialchars($row['Q1_SNoticemainsponsor'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeteam)%%>', htmlspecialchars($row['Q1_SNoticeteam'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeteam)%%>', htmlspecialchars($row['Q1_SNoticeteam'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeother)%%>', htmlspecialchars($row['Q1_SNoticeother'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeother)%%>', htmlspecialchars($row['Q1_SNoticeother'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Shavechangedview)%%>', htmlspecialchars($row['Q1_Shavechangedview'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Shavechangedview)%%>', htmlspecialchars($row['Q1_Shavechangedview'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Sbuyproducts)%%>', htmlspecialchars($row['Q1_Sbuyproducts'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Sbuyproducts)%%>', htmlspecialchars($row['Q1_Sbuyproducts'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Snameothers)%%>', htmlspecialchars($row['Q1_Snameothers'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Snameothers)%%>', htmlspecialchars($row['Q1_Snameothers'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Comments)%%>', htmlspecialchars($row['Q1_Comments'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Comments)%%>', htmlspecialchars($row['Q1_Comments'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_p_id)%%>', htmlspecialchars($row['Q1_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_p_id)%%>', htmlspecialchars($row['Q1_p_id'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(Q1_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_work)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_where)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_why)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_rating)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_speakothers)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_changedme)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_playoften)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_infolevel)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNotice)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticewhere)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticemainsponsor)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeteam)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_SNoticeother)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Shavechangedview)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Sbuyproducts)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Snameothers)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_Comments)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(Q1_p_id)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>