<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/Q1_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select Q1.Q1_id as 'ID', Q1.Q1_work as 'Work', Q1.Q1_where as 'Heard about Kemo-Kasper', Q1.Q1_why as 'Played Becaurse', Q1.Q1_rating as 'Rating DM', Q1.Q1_speakothers as 'Told others about', Q1.Q1_changedme as 'Changed my view on Cancer', Q1.Q1_playoften as 'Plays games', Q1.Q1_infolevel as 'Info about DM was', Q1.Q1_SNotice as 'Noticed Sponsors', Q1.Q1_SNoticewhere as 'Saw Sponsors here', sponsor12.s_id as 'Main Prize Sponsor', teams13.ts_name as 'Played for Team', Q1.Q1_SNoticeother as 'Q1_SNoticeother', Q1.Q1_Shavechangedview as 'Q1_Shavechangedview', Q1.Q1_Sbuyproducts as 'Q1_Sbuyproducts', Q1.Q1_Snameothers as 'Q1_Snameothers', Q1.Q1_Comments as 'Q1_Comments' from Q1 LEFT JOIN sponsor as sponsor12 ON Q1.Q1_SNoticemainsponsor=sponsor12.s_id LEFT JOIN teams as teams13 ON Q1.Q1_SNoticeteam=teams13.ts_id LEFT JOIN player as player19 ON Q1.Q1_p_id=player19.p_id ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select Q1.Q1_id as 'ID', Q1.Q1_work as 'Work', Q1.Q1_where as 'Heard about Kemo-Kasper', Q1.Q1_why as 'Played Becaurse', Q1.Q1_rating as 'Rating DM', Q1.Q1_speakothers as 'Told others about', Q1.Q1_changedme as 'Changed my view on Cancer', Q1.Q1_playoften as 'Plays games', Q1.Q1_infolevel as 'Info about DM was', Q1.Q1_SNotice as 'Noticed Sponsors', Q1.Q1_SNoticewhere as 'Saw Sponsors here', concat(sponsor12.s_id, ':', sponsor12.s_name) as 'Main Prize Sponsor', concat(teams13.ts_name, '') as 'Played for Team', Q1.Q1_SNoticeother as 'Q1_SNoticeother', Q1.Q1_Shavechangedview as 'Q1_Shavechangedview', Q1.Q1_Sbuyproducts as 'Q1_Sbuyproducts', Q1.Q1_Snameothers as 'Q1_Snameothers', Q1.Q1_Comments as 'Q1_Comments', concat(player19.p_id, ':', player19.p_mail) as 'Q1_p_id' from Q1 LEFT JOIN sponsor as sponsor12 ON Q1.Q1_SNoticemainsponsor=sponsor12.s_id LEFT JOIN teams as teams13 ON Q1.Q1_SNoticeteam=teams13.ts_id LEFT JOIN player as player19 ON Q1.Q1_p_id=player19.p_id ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Q1_view.php";
	$x->RedirectAfterInsert = "Q1_view.php?SelectedID=#ID#";
	$x->TableTitle = "Questions 1";
	$x->PrimaryKey = "Q1.Q1_id";

	$x->ColWidth   = array(150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 50);
	$x->ColCaption = array("Work", "Heard about Kemo-Kasper", "Played Becaurse", "Rating DM", "Told others about", "Changed my view on Cancer", "Plays games", "Info about DM was", "Noticed Sponsors", "Saw Sponsors here", "Main Prize Sponsor", "Played for Team", "Q1_SNoticeother", "Q1_Shavechangedview", "Q1_Sbuyproducts", "Q1_p_id");
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 19);

	$x->Template = 'Q1_templateTV.html';
	$x->SelectedTemplate = 'Q1_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>