<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/raffle_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select raffle.r_name as 'R_name', raffle.r_img as 'R_img', raffle.r_text as 'R_text', raffle.r_date as 'R_date', raffle.r_p_id as 'R_p_id' from raffle ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select raffle.r_id as 'R_id', raffle.r_name as 'R_name', if(length(raffle.r_img), concat('<img src=" . getUploadDir("") . "',raffle.r_img,' border=0>'), '') as 'R_img', raffle.r_text as 'R_text', if(raffle.r_date,date_format(raffle.r_date,'%m/%d/%Y'),'') as 'R_date', raffle.r_p_id as 'R_p_id' from raffle ";
	}
	
	// handle date sorting correctly
	if($HTTP_POST_VARS['SortField']=='5' || $HTTP_POST_VARS['SortField']=='raffle.r_date'){
		$HTTP_POST_VARS['SortField']='raffle.r_date';
		$SortFieldNumeric=5;
	}
	if($HTTP_GET_VARS['SortField']=='5' || $HTTP_GET_VARS['SortField']=='raffle.r_date'){
		$HTTP_GET_VARS['SortField']='raffle.r_date';
		$SortFieldNumeric=5;
	}
	// end of date sorting handler
	
	$x->DataHeight = 150;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "raffle_view.php";
	$x->RedirectAfterInsert = "raffle_view.php?SelectedID=#ID#";
	$x->TableTitle = "Prizes";
	$x->PrimaryKey = "raffle.r_id";
	$x->DefaultSortField = "5";
	$x->DefaultSortDirection = "asc";

	$x->ColWidth   = array(150, 150, 150);
	$x->ColCaption = array("R_name", "R_date", "R_p_id");
	$x->ColNumber  = array(2, 5, 6);

	$x->Template = 'raffle_templateTV.html';
	$x->SelectedTemplate = 'raffle_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>