<?php
/*   This application was generated by AppGini 3.4 on 07-11-2007 at 10:07:20
     Download AppGini for free from http://www.bigprof.com/appgini/download/ */

	$oHideTableView=$x->HideTableView;
	$oTableTitle=$x->TableTitle;
	$oAllowDelete=$x->AllowDelete;
	$oAllowUpdate=$x->AllowUpdate;
	$oAllowInsert=$x->AllowInsert;
	$addNewButton=(($oAllowInsert && $x->AllowSelection) ? " <input name=\"addNew\" type=\"image\" src=\"addNew.gif\">" : "");
	
	$x->AllowDelete=0;
	$x->AllowInsert=0;
	$x->AllowUpdate=0;
	$x->TableTitle=$oTableTitle.$addNewButton;
	if($HTTP_POST_VARS['SelectedID']!='' || $HTTP_GET_VARS['SelectedID']!='' || $HTTP_POST_VARS['addNew_x'] || $HTTP_GET_VARS['addNew_x'] || $HTTP_POST_VARS['insert_x'] || $HTTP_GET_VARS['insert_x']){
		$x->HideTableView=1;
		$x->TableTitle = "<input name=\"deselect\" type=\"image\" src=\"cancel.gif\">";
		$x->AllowDelete=$oAllowDelete;
		$x->AllowInsert=$oAllowInsert;
		$x->AllowUpdate=$oAllowUpdate;
		if(isset($HTTP_POST_VARS['update_x']) || isset($HTTP_GET_VARS['update_x']) || (isset($HTTP_GET_VARS['delete_x']) && (!$x->AllowDeleteOfParents || $HTTP_GET_VARS['confirmed']==1)) || (isset($HTTP_POST_VARS['delete_x']) && (!$x->AllowDeleteOfParents || $HTTP_POST_VARS['confirmed']==1))){
			$x->TableTitle="";
			?><div class="TableTitle"><?php echo $Translation['please wait']; ?> ...</div><META HTTP-EQUIV="Refresh" CONTENT="3;url=<?php echo basename($HTTP_SERVER_VARS['PHP_SELF']); ?>"><?php
		}
	}
	if(isset($HTTP_POST_VARS['deselect_x']) || isset($HTTP_GET_VARS['deselect_x']) || $HTTP_GET_VARS['NoDV']==1 || $HTTP_POST_VARS['NoDV']==1){
		$x->HideTableView=$oHideTableView;
		$x->TableTitle=$oTableTitle.$addNewButton;
		$x->AllowDelete=0;
		$x->AllowInsert=0;
		$x->AllowUpdate=0;
		$HTTP_POST_VARS['SelectedID']='';
		$HTTP_GET_VARS['SelectedID']='';
		if(isset($HTTP_POST_VARS['Print_x']) || isset($HTTP_GET_VARS['Print_x'])){
			$x->TableTitle=$oTableTitle;
		}
	}
?>