<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/sponsor_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select xstatus2.xs_text as 'Aktiv', sponsor.s_name as 'S_name', sponsor.s_contact as 'S_contact', sponsor.s_adr as 'S_adr', ZZIP6.ZZIP as 'S_zip', sponsor.s_phone1 as 'S_phone1', sponsor.s_phone2 as 'S_phone2', sponsor.s_total as 'S_total', sponsor.s_paid as 'S_paid', sponsor.s_www as 'S_www', sponsor.s_mail as 'S_mail', sponsor.s_cmt as 'S_cmt' from sponsor LEFT JOIN xstatus as xstatus2 ON sponsor.s_active=xstatus2.xs_id LEFT JOIN ZZIP as ZZIP6 ON sponsor.s_zip=ZZIP6.ZZIP ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select sponsor.s_id as 'Sid', concat(xstatus2.xs_text, '') as 'Aktiv', sponsor.s_name as 'S_name', sponsor.s_contact as 'S_contact', sponsor.s_adr as 'S_adr', concat(ZZIP6.ZZIP, '', ZZIP6.ZZCity) as 'S_zip', sponsor.s_phone1 as 'S_phone1', sponsor.s_phone2 as 'S_phone2', sponsor.s_total as 'S_total', sponsor.s_paid as 'S_paid', if(length(sponsor.s_logo), concat('<img src=" . getUploadDir("") . "',sponsor.s_logo,' border=0>'), '') as 'S_logo', if(length(sponsor.s_banner), concat('<img src=" . getUploadDir("") . "',sponsor.s_banner,' border=0>'), '') as 'S_banner', sponsor.s_www as 'S_www', sponsor.s_mail as 'S_mail', sponsor.s_cmt as 'S_cmt' from sponsor LEFT JOIN xstatus as xstatus2 ON sponsor.s_active=xstatus2.xs_id LEFT JOIN ZZIP as ZZIP6 ON sponsor.s_zip=ZZIP6.ZZIP ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "sponsor_view.php";
	$x->RedirectAfterInsert = "sponsor_view.php?SelectedID=#ID#";
	$x->TableTitle = "Sponsor";
	$x->PrimaryKey = "sponsor.s_id";
	$x->DefaultSortField = "3";
	$x->DefaultSortDirection = "asc";

	$x->ColWidth   = array(150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Aktiv", "S_name", "S_contact", "S_phone1", "S_banner", "S_mail");
	$x->ColNumber  = array(2, 3, 4, 7, 12, 14);

	$x->Template = 'sponsor_templateTV.html';
	$x->SelectedTemplate = 'sponsor_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>