<?php

// Data functions for table sponsor

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$s_active = $HTTP_POST_VARS["s_active"];
		$s_name = $HTTP_POST_VARS["s_name"];
		$s_contact = $HTTP_POST_VARS["s_contact"];
		$s_adr = $HTTP_POST_VARS["s_adr"];
		$s_zip = $HTTP_POST_VARS["s_zip"];
		$s_phone1 = $HTTP_POST_VARS["s_phone1"];
		$s_phone2 = $HTTP_POST_VARS["s_phone2"];
		$s_total = $HTTP_POST_VARS["s_total"];
		$s_paid = $HTTP_POST_VARS["s_paid"];
		$s_www = $HTTP_POST_VARS["s_www"];
		$s_mail = $HTTP_POST_VARS["s_mail"];
		$s_cmt = $HTTP_POST_VARS["s_cmt"];
	}
	else
	{
		$s_active = addslashes($HTTP_POST_VARS["s_active"]);
		$s_name = addslashes($HTTP_POST_VARS["s_name"]);
		$s_contact = addslashes($HTTP_POST_VARS["s_contact"]);
		$s_adr = addslashes($HTTP_POST_VARS["s_adr"]);
		$s_zip = addslashes($HTTP_POST_VARS["s_zip"]);
		$s_phone1 = addslashes($HTTP_POST_VARS["s_phone1"]);
		$s_phone2 = addslashes($HTTP_POST_VARS["s_phone2"]);
		$s_total = addslashes($HTTP_POST_VARS["s_total"]);
		$s_paid = addslashes($HTTP_POST_VARS["s_paid"]);
		$s_www = addslashes($HTTP_POST_VARS["s_www"]);
		$s_mail = addslashes($HTTP_POST_VARS["s_mail"]);
		$s_cmt = addslashes($HTTP_POST_VARS["s_cmt"]);
	}
	$s_logo = PrepareUploadedFile('s_logo', 80000,'jpg|jpeg|gif|png', false, "");
	$s_banner = PrepareUploadedFile('s_banner', 80000,'jpg|jpeg|gif|png', false, "");
	if($s_zip == "") $s_zip = "0";
	if($s_total == "") $s_total = "0";
	if($s_paid == "") $s_paid = "0";
	
	sql("insert into sponsor (s_active, s_name, s_contact, s_adr, s_zip, s_phone1, s_phone2, s_total, s_paid, s_logo, s_banner, s_www, s_mail, s_cmt) values (" . (($s_active != "") ? "'$s_active'" : "NULL") . ", " . (($s_name != "") ? "'$s_name'" : "NULL") . ", " . (($s_contact != "") ? "'$s_contact'" : "NULL") . ", " . (($s_adr != "") ? "'$s_adr'" : "NULL") . ", " . (($s_zip != "") ? "'$s_zip'" : "NULL") . ", " . (($s_phone1 != "") ? "'$s_phone1'" : "NULL") . ", " . (($s_phone2 != "") ? "'$s_phone2'" : "NULL") . ", " . (($s_total != "") ? "'$s_total'" : "NULL") . ", " . (($s_paid != "") ? "'$s_paid'" : "NULL") . ", " . (($s_logo != "") ? "'$s_logo'" : "NULL") . ", " . (($s_banner != "") ? "'$s_banner'" : "NULL") . ", " . (($s_www != "") ? "'$s_www'" : "NULL") . ", " . (($s_mail != "") ? "'$s_mail'" : "NULL") . ", " . (($s_cmt != "") ? "'$s_cmt'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;

	// child table: teams
	$res = sql("select s_id from sponsor where s_id='".addslashes($selected_id)."'");
	$s_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from teams where ts_s_id='".addslashes($s_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "teams", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "teams", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='sponsor_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='sponsor_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: Q1
	$res = sql("select s_id from sponsor where s_id='".addslashes($selected_id)."'");
	$s_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from Q1 where Q1_SNoticemainsponsor='".addslashes($s_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Q1", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Q1", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='sponsor_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='sponsor_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	

	// delete file stored in the 's_logo' field
	$res = sql("select s_logo from sponsor where s_id='".addslashes($selected_id)."'");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir("").$row[0]);
		}
	}

	// delete file stored in the 's_banner' field
	$res = sql("select s_banner from sponsor where s_id='".addslashes($selected_id)."'");
	if($row=@mysql_fetch_row($res)){
		if($row[0]!=''){
			@unlink(getUploadDir("").$row[0]);
		}
	}

	sql("delete from sponsor where s_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$s_active = $HTTP_POST_VARS["s_active"];
		$s_name = $HTTP_POST_VARS["s_name"];
		$s_contact = $HTTP_POST_VARS["s_contact"];
		$s_adr = $HTTP_POST_VARS["s_adr"];
		$s_zip = $HTTP_POST_VARS["s_zip"];
		$s_phone1 = $HTTP_POST_VARS["s_phone1"];
		$s_phone2 = $HTTP_POST_VARS["s_phone2"];
		$s_total = $HTTP_POST_VARS["s_total"];
		$s_paid = $HTTP_POST_VARS["s_paid"];
		$s_www = $HTTP_POST_VARS["s_www"];
		$s_mail = $HTTP_POST_VARS["s_mail"];
		$s_cmt = $HTTP_POST_VARS["s_cmt"];
	}
	else
	{
		$s_active = addslashes($HTTP_POST_VARS["s_active"]);
		$s_name = addslashes($HTTP_POST_VARS["s_name"]);
		$s_contact = addslashes($HTTP_POST_VARS["s_contact"]);
		$s_adr = addslashes($HTTP_POST_VARS["s_adr"]);
		$s_zip = addslashes($HTTP_POST_VARS["s_zip"]);
		$s_phone1 = addslashes($HTTP_POST_VARS["s_phone1"]);
		$s_phone2 = addslashes($HTTP_POST_VARS["s_phone2"]);
		$s_total = addslashes($HTTP_POST_VARS["s_total"]);
		$s_paid = addslashes($HTTP_POST_VARS["s_paid"]);
		$s_www = addslashes($HTTP_POST_VARS["s_www"]);
		$s_mail = addslashes($HTTP_POST_VARS["s_mail"]);
		$s_cmt = addslashes($HTTP_POST_VARS["s_cmt"]);
	}

	if($HTTP_POST_VARS['s_logo_remove'] == 1){
		$s_logo = '';
		// delete file from server
		$res = sql("select s_logo from sponsor where s_id='$selected_id'");
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir("").$row[0]);
			}
		}
	}else{
		$s_logo = PrepareUploadedFile('s_logo', 80000, 'jpg|jpeg|gif|png', false, "");
		// delete file from server
		if($s_logo != ''){
			$res = sql("select s_logo from sponsor where s_id='$selected_id'");
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir("").$row[0]);
				}
			}
		}
	}
	if($HTTP_POST_VARS['s_banner_remove'] == 1){
		$s_banner = '';
		// delete file from server
		$res = sql("select s_banner from sponsor where s_id='$selected_id'");
		if($row=@mysql_fetch_row($res)){
			if($row[0]!=''){
				@unlink(getUploadDir("").$row[0]);
			}
		}
	}else{
		$s_banner = PrepareUploadedFile('s_banner', 80000, 'jpg|jpeg|gif|png', false, "");
		// delete file from server
		if($s_banner != ''){
			$res = sql("select s_banner from sponsor where s_id='$selected_id'");
			if($row=@mysql_fetch_row($res)){
				if($row[0]!=''){
					@unlink(getUploadDir("").$row[0]);
				}
			}
		}
	}
	sql("update sponsor set " . "s_active=" . (($s_active != "") ? "'$s_active'" : "NULL") . ", " . "s_name=" . (($s_name != "") ? "'$s_name'" : "NULL") . ", " . "s_contact=" . (($s_contact != "") ? "'$s_contact'" : "NULL") . ", " . "s_adr=" . (($s_adr != "") ? "'$s_adr'" : "NULL") . ", " . "s_zip=" . (($s_zip != "") ? "'$s_zip'" : "NULL") . ", " . "s_phone1=" . (($s_phone1 != "") ? "'$s_phone1'" : "NULL") . ", " . "s_phone2=" . (($s_phone2 != "") ? "'$s_phone2'" : "NULL") . ", " . "s_total=" . (($s_total != "") ? "'$s_total'" : "NULL") . ", " . "s_paid=" . (($s_paid != "") ? "'$s_paid'" : "NULL") . ", " . ($s_logo!="" ? "s_logo='$s_logo'" : ($HTTP_POST_VARS['s_logo_remove'] != 1 ? "s_logo=s_logo" : "s_logo=NULL")) . ", " . ($s_banner!="" ? "s_banner='$s_banner'" : ($HTTP_POST_VARS['s_banner_remove'] != 1 ? "s_banner=s_banner" : "s_banner=NULL")) . ", " . "s_www=" . (($s_www != "") ? "'$s_www'" : "NULL") . ", " . "s_mail=" . (($s_mail != "") ? "'$s_mail'" : "NULL") . ", " . "s_cmt=" . (($s_cmt != "") ? "'$s_cmt'" : "NULL") . " where s_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: s_active
	$combo_s_active = new DataCombo;
	$combo_s_active->Query = "select xs_id, concat(xs_text, '') from xstatus order by 2";
	$combo_s_active->SelectName = "s_active";
	// combobox: s_zip
	$combo_s_zip = new DataCombo;
	$combo_s_zip->Query = "select ZZIP, concat(ZZIP, '', ZZCity) from ZZIP order by 2";
	$combo_s_zip->SelectName = "s_zip";

	if($selected_id)
	{
		$res = sql("select * from sponsor where s_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_s_active->SelectedData = $row["s_active"];
		$combo_s_zip->SelectedData = $row["s_zip"];
	}
	$combo_s_active->Render();
	$combo_s_zip->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./sponsor_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(s_active)%%>', $combo_s_active->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(s_active)%%>', $combo_s_active->MatchText, $templateCode);
	$templateCode=str_replace('<%%COMBO(s_zip)%%>', $combo_s_zip->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(s_zip)%%>', $combo_s_zip->MatchText, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(s_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_active)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_contact)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_adr)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_zip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_phone1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_phone2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_total)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_paid)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_logo)%%>', '<input type=hidden name=MAX_FILE_SIZE value=80000>'.$Translation['upload image'].' <input type=file name="s_logo" class=TextBox>', $templateCode);
	if($AllowUpdate && $row['s_logo']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(s_logo)%%>', '<input type=checkbox name="s_logo_remove" value="1"> <b class=Error>'.$Translation['remove image'].'</b>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(s_logo)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(s_banner)%%>', '<input type=hidden name=MAX_FILE_SIZE value=80000>'.$Translation['upload image'].' <input type=file name="s_banner" class=TextBox>', $templateCode);
	if($AllowUpdate && $row['s_banner']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(s_banner)%%>', '<input type=checkbox name="s_banner_remove" value="1"> <b class=Error>'.$Translation['remove image'].'</b>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(s_banner)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(s_www)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_mail)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(s_cmt)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(s_id)%%>', htmlspecialchars($row['s_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_id)%%>', htmlspecialchars($row['s_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_active)%%>', htmlspecialchars($row['s_active'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%CHECKED(s_active)%%>', ($row['s_active'] ? "checked" : ""), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_name)%%>', htmlspecialchars($row['s_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_name)%%>', htmlspecialchars($row['s_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_contact)%%>', htmlspecialchars($row['s_contact'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_contact)%%>', htmlspecialchars($row['s_contact'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_adr)%%>', htmlspecialchars($row['s_adr'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_adr)%%>', htmlspecialchars($row['s_adr'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_zip)%%>', htmlspecialchars($row['s_zip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_zip)%%>', htmlspecialchars($row['s_zip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone1)%%>', htmlspecialchars($row['s_phone1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone1)%%>', htmlspecialchars($row['s_phone1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone2)%%>', htmlspecialchars($row['s_phone2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone2)%%>', htmlspecialchars($row['s_phone2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_total)%%>', htmlspecialchars($row['s_total'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_total)%%>', htmlspecialchars($row['s_total'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_paid)%%>', htmlspecialchars($row['s_paid'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_paid)%%>', htmlspecialchars($row['s_paid'], ENT_QUOTES), $templateCode);
		$row['s_logo']=($row['s_logo']!=''?$row['s_logo']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(s_logo)%%>', htmlspecialchars($row['s_logo'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_logo)%%>', htmlspecialchars($row['s_logo'], ENT_QUOTES), $templateCode);
		$row['s_banner']=($row['s_banner']!=''?$row['s_banner']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(s_banner)%%>', htmlspecialchars($row['s_banner'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_banner)%%>', htmlspecialchars($row['s_banner'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_www)%%>', htmlspecialchars($row['s_www'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_www)%%>', htmlspecialchars($row['s_www'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_mail)%%>', htmlspecialchars($row['s_mail'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_mail)%%>', htmlspecialchars($row['s_mail'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_cmt)%%>', htmlspecialchars($row['s_cmt'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(s_cmt)%%>', htmlspecialchars($row['s_cmt'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(s_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%CHECKED(s_active)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_contact)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_adr)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_zip)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_phone2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_total)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_paid)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_logo)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_banner)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_www)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_mail)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(s_cmt)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>