<?php

// Data functions for table teams

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$ts_name = $HTTP_POST_VARS["ts_name"];
		$ts_p0 = $HTTP_POST_VARS["ts_p0"];
		$ts_p1 = $HTTP_POST_VARS["ts_p1"];
		$ts_p2 = $HTTP_POST_VARS["ts_p2"];
		$ts_p3 = $HTTP_POST_VARS["ts_p3"];
		$ts_p4 = $HTTP_POST_VARS["ts_p4"];
		$ts_p5 = $HTTP_POST_VARS["ts_p5"];
		$ts_p6 = $HTTP_POST_VARS["ts_p6"];
		$ts_p7 = $HTTP_POST_VARS["ts_p7"];
		$ts_p8 = $HTTP_POST_VARS["ts_p8"];
		$ts_p9 = $HTTP_POST_VARS["ts_p9"];
		$ts_s_id = $HTTP_POST_VARS["ts_s_id"];
		$ts_Score = $HTTP_POST_VARS["ts_Score"];
	}
	else
	{
		$ts_name = addslashes($HTTP_POST_VARS["ts_name"]);
		$ts_p0 = addslashes($HTTP_POST_VARS["ts_p0"]);
		$ts_p1 = addslashes($HTTP_POST_VARS["ts_p1"]);
		$ts_p2 = addslashes($HTTP_POST_VARS["ts_p2"]);
		$ts_p3 = addslashes($HTTP_POST_VARS["ts_p3"]);
		$ts_p4 = addslashes($HTTP_POST_VARS["ts_p4"]);
		$ts_p5 = addslashes($HTTP_POST_VARS["ts_p5"]);
		$ts_p6 = addslashes($HTTP_POST_VARS["ts_p6"]);
		$ts_p7 = addslashes($HTTP_POST_VARS["ts_p7"]);
		$ts_p8 = addslashes($HTTP_POST_VARS["ts_p8"]);
		$ts_p9 = addslashes($HTTP_POST_VARS["ts_p9"]);
		$ts_s_id = addslashes($HTTP_POST_VARS["ts_s_id"]);
		$ts_Score = addslashes($HTTP_POST_VARS["ts_Score"]);
	}
	if($ts_Score == "") $ts_Score = "0";
	
	sql("insert into teams (ts_name, ts_p0, ts_s_id, ts_Score) values (" . (($ts_name != "") ? "'$ts_name'" : "NULL") . ", " . (($ts_p0 != "") ? "'$ts_p0'" : "NULL") . ", " . (($ts_s_id != "") ? "'$ts_s_id'" : "NULL") . ", " . (($ts_Score != "") ? "'$ts_Score'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;

	// child table: player
	$res = sql("select ts_id from teams where ts_id='".addslashes($selected_id)."'");
	$ts_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from player where p_s_id='".addslashes($ts_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='teams_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='teams_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: Q1
	$res = sql("select ts_id from teams where ts_id='".addslashes($selected_id)."'");
	$ts_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from Q1 where Q1_SNoticeteam='".addslashes($ts_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Q1", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Q1", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='teams_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='teams_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	

	sql("delete from teams where ts_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$ts_name = $HTTP_POST_VARS["ts_name"];
		$ts_p0 = $HTTP_POST_VARS["ts_p0"];
		$ts_p1 = $HTTP_POST_VARS["ts_p1"];
		$ts_p2 = $HTTP_POST_VARS["ts_p2"];
		$ts_p3 = $HTTP_POST_VARS["ts_p3"];
		$ts_p4 = $HTTP_POST_VARS["ts_p4"];
		$ts_p5 = $HTTP_POST_VARS["ts_p5"];
		$ts_p6 = $HTTP_POST_VARS["ts_p6"];
		$ts_p7 = $HTTP_POST_VARS["ts_p7"];
		$ts_p8 = $HTTP_POST_VARS["ts_p8"];
		$ts_p9 = $HTTP_POST_VARS["ts_p9"];
		$ts_s_id = $HTTP_POST_VARS["ts_s_id"];
		$ts_Score = $HTTP_POST_VARS["ts_Score"];
	}
	else
	{
		$ts_name = addslashes($HTTP_POST_VARS["ts_name"]);
		$ts_p0 = addslashes($HTTP_POST_VARS["ts_p0"]);
		$ts_p1 = addslashes($HTTP_POST_VARS["ts_p1"]);
		$ts_p2 = addslashes($HTTP_POST_VARS["ts_p2"]);
		$ts_p3 = addslashes($HTTP_POST_VARS["ts_p3"]);
		$ts_p4 = addslashes($HTTP_POST_VARS["ts_p4"]);
		$ts_p5 = addslashes($HTTP_POST_VARS["ts_p5"]);
		$ts_p6 = addslashes($HTTP_POST_VARS["ts_p6"]);
		$ts_p7 = addslashes($HTTP_POST_VARS["ts_p7"]);
		$ts_p8 = addslashes($HTTP_POST_VARS["ts_p8"]);
		$ts_p9 = addslashes($HTTP_POST_VARS["ts_p9"]);
		$ts_s_id = addslashes($HTTP_POST_VARS["ts_s_id"]);
		$ts_Score = addslashes($HTTP_POST_VARS["ts_Score"]);
	}

	sql("update teams set " . "ts_name=" . (($ts_name != "") ? "'$ts_name'" : "NULL") . ", " . "ts_p0=" . (($ts_p0 != "") ? "'$ts_p0'" : "NULL") . ", " . "ts_s_id=" . (($ts_s_id != "") ? "'$ts_s_id'" : "NULL") . ", " . "ts_Score=" . (($ts_Score != "") ? "'$ts_Score'" : "NULL") . " where ts_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	
	// combobox: ts_s_id
	$combo_ts_s_id = new DataCombo;
	$combo_ts_s_id->Query = "select s_id, concat(s_name, '') from sponsor order by 2";
	$combo_ts_s_id->SelectName = "ts_s_id";

	if($selected_id)
	{
		$res = sql("select * from teams where ts_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
		$combo_ts_s_id->SelectedData = $row["ts_s_id"];
	}
	$combo_ts_s_id->Render();
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./teams_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	$templateCode=str_replace('<%%COMBO(ts_s_id)%%>', $combo_ts_s_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(ts_s_id)%%>', $combo_ts_s_id->MatchText, $templateCode);
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ts_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p0)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p3)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p4)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p5)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p6)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p7)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p8)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_p9)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_s_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ts_Score)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ts_id)%%>', htmlspecialchars($row['ts_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_id)%%>', htmlspecialchars($row['ts_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_name)%%>', htmlspecialchars($row['ts_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_name)%%>', htmlspecialchars($row['ts_name'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p0)%%>', htmlspecialchars($row['ts_p0'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p0)%%>', htmlspecialchars($row['ts_p0'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p1)%%>', htmlspecialchars($row['ts_p1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p1)%%>', htmlspecialchars($row['ts_p1'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p2)%%>', htmlspecialchars($row['ts_p2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p2)%%>', htmlspecialchars($row['ts_p2'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p3)%%>', htmlspecialchars($row['ts_p3'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p3)%%>', htmlspecialchars($row['ts_p3'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p4)%%>', htmlspecialchars($row['ts_p4'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p4)%%>', htmlspecialchars($row['ts_p4'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p5)%%>', htmlspecialchars($row['ts_p5'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p5)%%>', htmlspecialchars($row['ts_p5'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p6)%%>', htmlspecialchars($row['ts_p6'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p6)%%>', htmlspecialchars($row['ts_p6'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p7)%%>', htmlspecialchars($row['ts_p7'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p7)%%>', htmlspecialchars($row['ts_p7'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p8)%%>', htmlspecialchars($row['ts_p8'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p8)%%>', htmlspecialchars($row['ts_p8'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p9)%%>', htmlspecialchars($row['ts_p9'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p9)%%>', htmlspecialchars($row['ts_p9'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_s_id)%%>', htmlspecialchars($row['ts_s_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_s_id)%%>', htmlspecialchars($row['ts_s_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_Score)%%>', htmlspecialchars($row['ts_Score'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_Score)%%>', htmlspecialchars($row['ts_Score'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ts_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p0)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p4)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p5)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p6)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p7)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p8)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_p9)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_s_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ts_Score)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>