<?php

// Data functions for table top

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$t_user = $HTTP_POST_VARS["t_user"];
		$t_score = $HTTP_POST_VARS["t_score"];
		$t_datetime = $HTTP_POST_VARS["t_datetime"];
		$t_ip = $HTTP_POST_VARS["t_ip"];
		$t_p_id = $HTTP_POST_VARS["t_p_id"];
		$t_ts_id = $HTTP_POST_VARS["t_ts_id"];
		$t_kills = $HTTP_POST_VARS["t_kills"];
	}
	else
	{
		$t_user = addslashes($HTTP_POST_VARS["t_user"]);
		$t_score = addslashes($HTTP_POST_VARS["t_score"]);
		$t_datetime = addslashes($HTTP_POST_VARS["t_datetime"]);
		$t_ip = addslashes($HTTP_POST_VARS["t_ip"]);
		$t_p_id = addslashes($HTTP_POST_VARS["t_p_id"]);
		$t_ts_id = addslashes($HTTP_POST_VARS["t_ts_id"]);
		$t_kills = addslashes($HTTP_POST_VARS["t_kills"]);
	}
	if($t_kills == "") $t_kills = "0";
	
	sql("insert into top (t_user, t_score, t_datetime, t_p_id, t_ts_id) values (" . (($t_user != "") ? "'$t_user'" : "NULL") . ", " . (($t_score != "") ? "'$t_score'" : "NULL") . ", " . (($t_datetime != "") ? "'$t_datetime'" : "NULL") . ", " . (($t_p_id != "") ? "'$t_p_id'" : "NULL") . ", " . (($t_ts_id != "") ? "'$t_ts_id'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;


	sql("delete from top where t_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$t_user = $HTTP_POST_VARS["t_user"];
		$t_score = $HTTP_POST_VARS["t_score"];
		$t_datetime = $HTTP_POST_VARS["t_datetime"];
		$t_ip = $HTTP_POST_VARS["t_ip"];
		$t_p_id = $HTTP_POST_VARS["t_p_id"];
		$t_ts_id = $HTTP_POST_VARS["t_ts_id"];
		$t_kills = $HTTP_POST_VARS["t_kills"];
	}
	else
	{
		$t_user = addslashes($HTTP_POST_VARS["t_user"]);
		$t_score = addslashes($HTTP_POST_VARS["t_score"]);
		$t_datetime = addslashes($HTTP_POST_VARS["t_datetime"]);
		$t_ip = addslashes($HTTP_POST_VARS["t_ip"]);
		$t_p_id = addslashes($HTTP_POST_VARS["t_p_id"]);
		$t_ts_id = addslashes($HTTP_POST_VARS["t_ts_id"]);
		$t_kills = addslashes($HTTP_POST_VARS["t_kills"]);
	}

	sql("update top set " . "t_user=" . (($t_user != "") ? "'$t_user'" : "NULL") . ", " . "t_score=" . (($t_score != "") ? "'$t_score'" : "NULL") . ", " . "t_datetime=" . (($t_datetime != "") ? "'$t_datetime'" : "NULL") . ", " . "t_p_id=" . (($t_p_id != "") ? "'$t_p_id'" : "NULL") . ", " . "t_ts_id=" . (($t_ts_id != "") ? "'$t_ts_id'" : "NULL") . " where t_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	

	if($selected_id)
	{
		$res = sql("select * from top where t_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
	}
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./top_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(t_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_user)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_score)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_datetime)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_ip)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_p_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_ts_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(t_kills)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(t_id)%%>', htmlspecialchars($row['t_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_id)%%>', htmlspecialchars($row['t_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_user)%%>', htmlspecialchars($row['t_user'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_user)%%>', htmlspecialchars($row['t_user'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_score)%%>', htmlspecialchars($row['t_score'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_score)%%>', htmlspecialchars($row['t_score'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_datetime)%%>', htmlspecialchars($row['t_datetime'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_datetime)%%>', htmlspecialchars($row['t_datetime'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ip)%%>', htmlspecialchars($row['t_ip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ip)%%>', htmlspecialchars($row['t_ip'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_p_id)%%>', htmlspecialchars($row['t_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_p_id)%%>', htmlspecialchars($row['t_p_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ts_id)%%>', htmlspecialchars($row['t_ts_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ts_id)%%>', htmlspecialchars($row['t_ts_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_kills)%%>', htmlspecialchars($row['t_kills'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(t_kills)%%>', htmlspecialchars($row['t_kills'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(t_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_user)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_score)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_datetime)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ip)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_p_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_ts_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(t_kills)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>