<?php
// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:19
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	include(dirname(__FILE__)."/language.php");
	include(dirname(__FILE__)."/lib.php");
	include(dirname(__FILE__)."/top_dml.php");
	
	$x = new DataList;
	if($HTTP_POST_VARS["Filter_x"] != ""  || $HTTP_POST_VARS['CSV_x'] != "")
	{
		// Query used in filters page and CSV output
		$x->Query = "select top.t_id as 'T_id', top.t_user as 'T_user', top.t_score as 'T_score', top.t_datetime as 'T_datetime', top.t_ip as 'IP Address', top.t_p_id as 'T_p_id', top.t_ts_id as 'T_ts_id', top.t_kills as 'T_kills' from top ";
	}
	else
	{
		// Query used in table view
		$x->Query = "select top.t_id as 'T_id', top.t_user as 'T_user', top.t_score as 'T_score', top.t_datetime as 'T_datetime', top.t_ip as 'IP Address', top.t_p_id as 'T_p_id', top.t_ts_id as 'T_ts_id', top.t_kills as 'T_kills' from top ";
	}
	
	// handle date sorting correctly
	// end of date sorting handler
	
	$x->DataHeight = 450;
	$x->AllowSelection = 1;
	$x->AllowDelete = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowInsert = 1;
	$x->AllowUpdate = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 0;
	$x->HideTableView = 0;
	$x->RecordsPerPage = 30;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "top_view.php";
	$x->RedirectAfterInsert = "top_view.php?SelectedID=#ID#";
	$x->TableTitle = "Top Scores";
	$x->PrimaryKey = "top.t_id";
	$x->DefaultSortField = "4";
	$x->DefaultSortDirection = "desc";

	$x->ColWidth   = array(150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("T_user", "T_score", "T_datetime", "IP Address", "T_p_id", "T_ts_id", "T_kills");
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	$x->Template = 'top_templateTV.html';
	$x->SelectedTemplate = 'top_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 1;
	$x->HighlightColor = '#FFF0C2';

	// uncomment the following line to display the detail view in a separate page
	// include(dirname(__FILE__)."/separateDVTV.php");
	$x->Render();
	
	include(dirname(__FILE__)."/header.php");
	echo $x->HTML;
	include(dirname(__FILE__)."/footer.php");
?>