<?php

// Data functions for table xstatus

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$xs_text = $HTTP_POST_VARS["xs_text"];
	}
	else
	{
		$xs_text = addslashes($HTTP_POST_VARS["xs_text"]);
	}
	if($xs_text == "") $xs_text = "''";
	
	sql("insert into xstatus (xs_text) values (" . (($xs_text != "") ? "'$xs_text'" : "NULL") . ")");
	return mysql_insert_id();
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;

	// child table: player
	$res = sql("select xs_id from xstatus where xs_id='".addslashes($selected_id)."'");
	$xs_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from player where p_active='".addslashes($xs_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: sponsor
	$res = sql("select xs_id from xstatus where xs_id='".addslashes($selected_id)."'");
	$xs_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from sponsor where s_active='".addslashes($xs_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "sponsor", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "sponsor", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: news
	$res = sql("select xs_id from xstatus where xs_id='".addslashes($selected_id)."'");
	$xs_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from news where n_active='".addslashes($xs_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "news", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "news", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: locations
	$res = sql("select xs_id from xstatus where xs_id='".addslashes($selected_id)."'");
	$xs_id = mysql_fetch_row($res);
	$rires = sql("select count(1) from locations where l_active='".addslashes($xs_id[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "locations", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "locations", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='xstatus_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	

	sql("delete from xstatus where xs_id='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$xs_text = $HTTP_POST_VARS["xs_text"];
	}
	else
	{
		$xs_text = addslashes($HTTP_POST_VARS["xs_text"]);
	}

	sql("update xstatus set " . "xs_text=" . (($xs_text != "") ? "'$xs_text'" : "NULL") . " where xs_id='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	

	if($selected_id)
	{
		$res = sql("select * from xstatus where xs_id='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
	}
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./xstatus_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(xs_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(xs_text)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(xs_id)%%>', htmlspecialchars($row['xs_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(xs_id)%%>', htmlspecialchars($row['xs_id'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(xs_text)%%>', htmlspecialchars($row['xs_text'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(xs_text)%%>', htmlspecialchars($row['xs_text'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(xs_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(xs_text)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>