<?php

// Data functions for table ZZIP

// This script and data application were generated by AppGini 3.4 on 07-11-2007 at 10:07:20
// Download AppGini for free from http://www.bigprof.com/appgini/download/

function insert()
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $HTTP_POST_FILES, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$ZZIP = $HTTP_POST_VARS["ZZIP"];
		$ZZCity = $HTTP_POST_VARS["ZZCity"];
	}
	else
	{
		$ZZIP = addslashes($HTTP_POST_VARS["ZZIP"]);
		$ZZCity = addslashes($HTTP_POST_VARS["ZZCity"]);
	}
	if($ZZIP == "") {echo StyleSheet() . "\n\n<div class=Error>" . $Translation["error:"] . " 'ZZIP': " . $Translation['pkfield empty'] . "</div>"; exit;}

	if($ZZIP == "") $ZZIP = "0";
	
	sql("insert into ZZIP (ZZIP, ZZCity) values (" . (($ZZIP != "") ? "'$ZZIP'" : "NULL") . ", " . (($ZZCity != "") ? "'$ZZCity'" : "NULL") . ")");
	return $ZZIP;
}

function delete($selected_id, $AllowDeleteOfParents=false, $SkipChecks=false){
	// insure referential integrity ...
	global $Translation;

	// child table: player
	$res = sql("select ZZIP from ZZIP where ZZIP='".addslashes($selected_id)."'");
	$ZZIP = mysql_fetch_row($res);
	$rires = sql("select count(1) from player where p_zip='".addslashes($ZZIP[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "player", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: sponsor
	$res = sql("select ZZIP from ZZIP where ZZIP='".addslashes($selected_id)."'");
	$ZZIP = mysql_fetch_row($res);
	$rires = sql("select count(1) from sponsor where s_zip='".addslashes($ZZIP[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "sponsor", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "sponsor", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	
	// child table: locations
	$res = sql("select ZZIP from ZZIP where ZZIP='".addslashes($selected_id)."'");
	$ZZIP = mysql_fetch_row($res);
	$rires = sql("select count(1) from locations where l_zip='".addslashes($ZZIP[0])."'");
	$rirow = mysql_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "locations", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$SkipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "locations", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=button class=button value=\"".$Translation['yes']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=button class=button value=\"".$Translation['no']."\" onClick=\"window.location='ZZIP_view.php?SelectedID=$selected_id';\">", $RetMsg);
		return $RetMsg;
	}
	

	sql("delete from ZZIP where ZZIP='".addslashes($selected_id)."'");
}

function update($selected_id)
{
	global $HTTP_SERVER_VARS, $HTTP_GET_VARS, $HTTP_POST_VARS, $Translation;
	
	if(get_magic_quotes_gpc())
	{
		$ZZIP = $HTTP_POST_VARS["ZZIP"];
		$ZZCity = $HTTP_POST_VARS["ZZCity"];
	}
	else
	{
		$ZZIP = addslashes($HTTP_POST_VARS["ZZIP"]);
		$ZZCity = addslashes($HTTP_POST_VARS["ZZCity"]);
	}

	sql("update ZZIP set " . "ZZIP=" . (($ZZIP != "") ? "'$ZZIP'" : "NULL") . ", " . "ZZCity=" . (($ZZCity != "") ? "'$ZZCity'" : "NULL") . " where ZZIP='".addslashes($selected_id)."'");
}

function form($selected_id = "", $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1)
{
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.
	
	global $Translation;
	
	if(!$AllowInsert && $selected_id==""){  return ""; }
	
	

	if($selected_id)
	{
		$res = sql("select * from ZZIP where ZZIP='".addslashes($selected_id)."'");
		$row = mysql_fetch_array($res);
	}
	
	// code for template based detail view forms
	
	// open the detail view template
	$templateCode=@implode('', @file('./ZZIP_templateDV.html'));
	
	// process form title
	$templateCode=str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	// process buttons
	if($AllowInsert){
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', "<input type=image src=insert.gif name=insert alt='" . $Translation['add new record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}
	if($selected_id){
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', "<input type=image src=update.gif vspace=1 name=update alt='" . $Translation["update record"] . "'>", $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if($AllowDelete){
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', "<input type=image src=delete.gif vspace=1 name=delete alt='" . $Translation['delete record'] . "' onClick=\"return confirm('" . $Translation['are you sure?'] . "');\">", $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', "<input type=image src=deselect.gif vspace=1 name=deselect alt='" . $Translation['deselect record'] . "'>", $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}
	
	// process combos
	
	// process images
	$templateCode=str_replace('<%%UPLOADFILE(ZZIP)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ZZCity)%%>', '', $templateCode);
	
	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(ZZIP)%%>', htmlspecialchars($row['ZZIP'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ZZIP)%%>', htmlspecialchars($row['ZZIP'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ZZCity)%%>', htmlspecialchars($row['ZZCity'], ENT_QUOTES), $templateCode);
		$templateCode=str_replace('<%%VALUE(ZZCity)%%>', htmlspecialchars($row['ZZCity'], ENT_QUOTES), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(ZZIP)%%>', '', $templateCode);
		$templateCode=str_replace('<%%VALUE(ZZCity)%%>', '', $templateCode);
	}
	
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}
	
	// finally, clear scrap
	$templateCode=str_replace('<%%', '<!--', $templateCode);
	$templateCode=str_replace('%%>', '-->', $templateCode);

	return $templateCode;
}
?>